<?php

    $absolute_path = explode('wp-content', $_SERVER['SCRIPT_FILENAME']);
    $wp_load = $absolute_path[0] . 'wp-load.php';
    require_once($wp_load);

    header("Content-type: text/css; charset: UTF-8");
    header('Cache-control: must-revalidate');
    ?>

/* Custom styling dynamically generated by WordPress */

<?php if(get_option('psp_accent_color_1')): ?>
#psp-projects #psp-phases .psp-phase h3,
#psp-projects .psp-task-list li em.status,
#psp-projects p.psp-progress span, #psp-projects .psp-progress span,
#psp-projects ul.psp-milestones li.completed span {
    background: <?php echo get_option('psp_accent_color_1'); ?>;
    color: <?php echo get_option('psp_accent_color_1_txt'); ?>;
}
<?php endif; ?>

<?php if(get_option('psp_accent_color_2')): ?>
#psp-projects #psp-phases .psp-phase.color-teal h3,
#psp-projects .color-teal .psp-task-list li em.status {
    background: <?php echo get_option('psp_accent_color_2'); ?> !important;
    color: <?php echo get_option('psp_accent_color_2_txt'); ?>;
}
<?php endif; ?>

<?php if(get_option('psp_accent_color_3')): ?>
#psp-projects #psp-phases .psp-phase.color-green h3,
#psp-projects .color-green .psp-task-list li em.status {
    background: <?php echo get_option('psp_accent_color_3'); ?> !important;
    color: <?php echo get_option('psp_accent_color_3_txt'); ?>;
}
<?php endif; ?>

<?php if(get_option('psp_accent_color_4')): ?>
#psp-projects #psp-phases .psp-phase.color-pink h3,
#psp-projects .color-pink .psp-task-list li em.status {
    background: <?php echo get_option('psp_accent_color_4'); ?> !important;
    color: <?php echo get_option('psp_accent_color_4_txt'); ?>;
}
<?php endif; ?>

<?php if(get_option('psp_accent_color_5')): ?>
#psp-projects #psp-phases .psp-phase.color-maroon h3,
#psp-projects .color-maroon .psp-task-list li em.status {
    background: <?php echo get_option('psp_accent_color_5'); ?> !important;
    color: <?php echo get_option('psp_accent_color_5_txt'); ?>;
}
<?php endif; ?>

<?php if(get_option('psp_timeline_color')): ?>
	#psp-projects .psp-time-bar span,
	#psp-projects ol.psp-time-ticks li.active,
	#psp-projects .psp-date .cal .month {
		background: <?php echo get_option('psp_timeline_color'); ?>
	}

	#psp-projects .psp-time-indicator span {
		border-bottom-color: <?php echo get_option('psp_timeline_color'); ?>
	}
<?php endif; ?>

#psp-projects #psp-title #psp-main-nav #nav-menu ul li a {
    color: <?php echo get_option('psp_menu_text'); ?>;
}

#psp-projects #psp-title span {
    color: <?php echo get_option('psp_header_accent'); ?>;
}

body.psp-standalone-page,
#psp-projects,
#psp-projects.psp-standard-template {
    background-color: <?php echo get_option('psp_body_background'); ?>;
}

#psp-projects.psp-part-project,
#psp-projects.psp-single-project {
	background: transparent;
}

#psp-projects .psp-phase,
#psp-projects #psp-phases {
    border-color: <?php echo get_option('psp_body_background'); ?>;
}

#psp-projects #project-documents,
#psp-projects #psp-essentials div h4,
#psp-projects .psp-timing li,
#psp-projects .psp-time-start-end,
#psp-projects .psp-time-indicator {
    color: <?php echo get_option('psp_body_text'); ?>;
}

#psp-projects #project-documents ul li a {
    color: <?php echo get_option('psp_body_link'); ?>;
}

#psp-projects #project-documents h3 {
    color: <?php echo get_option('psp_body_heading'); ?>;
}

#psp-projects #psp-discussion {
    background-color: <?php echo get_option('psp_footer_background'); ?>;
}

<?php echo get_option('psp_open_css'); ?>
